---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-state-metrics
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 4.9.2
    helm:
      values: |
        nfs:
          server: 192.168.1.11
          path: /volume1/NFS
        storageClass:
          defaultClass: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-state-metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true   