---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 10.20.1
    helm:
      values: |
        additionalArguments:
          - --serversTransport.insecureSkipVerify=true      
        providers:
          kubernetesIngress:
            enabled: false
        logs:
          general:
            level: ERROR
          access:
            enabled: true
        service:
          spec:
            loadBalancerIP: 192.168.6.101                
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true   