---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 10.20.1
    helm:
      values: |
        additionalArguments:
          - --serversTransport.insecureSkipVerify=true      
        providers:
          kubernetesIngress:
            enabled: false
        logs:
          general:
            level: ERROR
          access:
            enabled: false
        service:
          spec:
            loadBalancerIP: 192.168.6.101  
        pilot:
          enabled: true
          token: "452473e6-6121-4e0a-ba13-1bb66d8088d9"     
        persistence:
          enabled: true
        initContainers:
          - name: volume-permissions
            image: busybox:1.31.1
            command: ["sh", "-c", "chmod -Rv 600 /data/*"]
            volumeMounts:
              - name: data
                mountPath: /data          
        certResolvers:
          letsencrypt:
            # for challenge options cf. https://doc.traefik.io/traefik/https/acme/
            email: tylerklier@gmail.com
            dnsChallenge:
              # also add the provider's required configuration under env
              # or expand then from secrets/configmaps with envfrom
              # cf. https://doc.traefik.io/traefik/https/acme/#providers
              provider: cloudflare
              # add futher options for the dns challenge as needed
              # cf. https://doc.traefik.io/traefik/https/acme/#dnschallenge
              delayBeforeCheck: 30
              resolvers:
                - 1.1.1.1
                - 8.8.8.8
            storage: /data/acme.json
        env:
          - name: CLOUDFLARE_EMAIL
            value: tylerklier@gmail.com
          - name: CLOUDFLARE_DNS_API_TOKEN
            value: bdea18e908eaf9153ffc3796638a3ce2a8223      
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true   