apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  source:
    path: test
    repoURL: https://github.com/DBAverage/k8s.git
    targetRevision: main    
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  
