---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rancher
  namespace: cattle-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`rancher.mushroomkingdom.io`)
      priority: 10
      services:
        - name: rancher
          port: 80
  tls:
    certResolver: default