---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: transmission
  namespace: transmission
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`transmission.mushroomkingdom.io`)
      services:
        - name: transmission
          port: 9091