apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-auth
  namespace: keycloak
spec:
  encryptedData:
    password: AgBtxku6/yk2LfiX6yn4QOjx/5ImQ61Y3lQM1+wKuwyK+uvmVvI7NtgapDq2L7XLP8Gbqiy/8BIymnPeXWWCyaUZlkTLMwBNq9clMauutebiqXncGQHwL8TM0JbyJ9kBXjjb4DtMy7DFg1EUAIx1g7hO6Go41lP+l/QWZWhOXOTt6xEPMyib4o5iXMMipQYxiaPH+w1HQ6xp/90VfxxVJoBrE4Lfa18JlQiUlyRjXOhQiWjqC4kpWVxP3CuAtSmGYZjWH8cWL4PaMvvU2O1tRFg1Kbs+m0/ZqSM5pNL82zy8ZHKZxekAUV5WRPwJxHn0eQ/yQWSmdlPpnF3GEHrGKXVXs/pDhyLoXo6Ty/2J7W9puI3VDKdLzCRyg2kSmpShL3JhfsStGAINqpbGFyzNm2+pEUfL185Tiuynx0Ndcf7xVeowQfJ7+p8n/mzCsnI0ukDlmL/rWSZceSUoYZ4qrQXH6AEKvDCPj7B9ZbVBWu72jovZjnSzyh4w3trObVYGy/OSMUUOzGwQwAx6hvs0QRLOL0DRkX6xWlHrGaG4jN0/+PlYkEctH2Ar/AcMi8z4mDDYmIreO7OkDwDb//JmBmud3TVyHJLugXPLQKXCwBj7puI6PR4nj2PkC2vJ4pdzTExTly9grOB8J2DMsTxx0PaEkRVXRRawMVFuggeeYNiv6vbXEMLthu7Zfl3dUxr664OxK4UGFlkD3HTF75tP
    user: AgBxViU690uITAY4Q7onVIYW0uBDrtXT9lT47lFwJu5+dfCTFiYF2wIJBF9F6aWkEzJZYfUpJIKH5pkVm3f8bKK3WRK0W7T8+nHuTl/6VUt2WrdaW/FJaxOjrbOTGKsXey9wzu14dFYdVKm6yj9kRRjPTsgTZrfMxt8EKc2tviM5hrCOgrCpUqGumbc6foth/goTWNc7BI52ODPfqXm6uhFH2kmIbccrZYkyZ4uj9o092NaxZUwlOKxj2tb1Q8W0yG0MSZYj3VbqvxTUW+ivjEIN3Wwx434R5x6Y21MdLl/TA7m5E/4GO0/CYnVsPDA8FxOnKmbQb+QT800K6DNIxz1Tjm8rQkj4f4dJIT0dSFQ2sc1+dpIBHUAnaSPDSkll76DjBFad0WCsgs1mOccmtzC+ZAcWjWncrIah6nQsbpOShkACghfrelKuEmi6sSKlMdFi4+s3UEdgx3/isk29KBDdJFg5Zr6rL8GG8cZAzxwNG4Z78I+Xu8Y3bStzcGZlBdpN4vxx+Y4060Ns3Sf+huitvH9sFGEY2ir8UtzMuSu+v7UnuVDteQ/ZRkDAi1PJq1ACv5nAsEmG014IguIO+WcJntNcjdaBj76hIK99DABHz61lvTJgjzw3ao2XjhtToFmAgIngNj4ScUVD0tpAGS4Y2cnY8eeoORuiVsDdS0J7RhvWT4qCrkv5NLiPEBN7sZGScDrX6w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-auth
      namespace: keycloak