---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 36.0.3
    helm:
      values: |
        prometheus:
              prometheusSpec:
                podMonitorNamespaceSelector: {}
                podMonitorSelector: {}
                podMonitorSelectorNilUsesHelmValues: false
                ruleNamespaceSelector: {}
                ruleSelector: {}
                ruleSelectorNilUsesHelmValues: false
                serviceMonitorNamespaceSelector: {}
                serviceMonitorSelector: {}
                serviceMonitorSelectorNilUsesHelmValues: false      
        grafana:
          admin:
            existingSecret: grafana-admin
            userKey: username
            passwordKey: password            
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true   