apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgBP6YlyqDb6rslWeuWl4fcnXnvaAj2RGPuD1J4tYxrWrb+UK7fqpT2mKZXXu78QW8XsWx3GJqPWLbONki5LyNvp1jjg9GFt8CNKW5El4WBSuZiTgKUsFcOqKd1iINjWxmuloD1UH0JZUcPkv2Gs1JjQUjsNDKSvjTJpI6jhGJQjV02oNQYOIFmyjRdJPiFmm1din+Rknp+NVjcn53reJQJdYM53cfrwsiUSUYqFu74JUkE8UTS8vwTQnMQ6DIFLBsYJEC4ywpKHFoyWzU6Pgofgq1T8c/UVjHGFDkJlW03Pyoa6p9Ce8BOWtJxS3WZ+mZh49tMoRZD0KiIFk2XPwYRXMtZptNWpyhLxjaFeksenHP9sxE2NBTQI0uKHtofvkT0rKWoCxBqyaIJYpTZhEZOdrRxVHe+VSkoc3eEP375hye2phLPzIF7NktQk7Tl6EDyB5ljQyX/JlFAwnZ0Hdgmg+sDDNuvtFcj+lGl749zriPyK73z2lCQEE/zS8lbf2ngtj5rEnzs58UHrujR4f7s7vzTtUJdFycRorve5wsnxDHpqhbaPj6tJ2n+Z4NRi8JAtChDC6Sm3hdZCdYdIB5SNYyvXHoUqc0ZKLT5o0VDjntoDho7d5QWQrKhy4yE4U7YC3y2FhydNsgFDhsM6AbBPOGca5NTWQxc0vZDcn9JK+5GODCsLMObT6PXgXNBJU/oWS+ivLc9d8qR5BNy1
    username: AgBBhWr9uIJms0QEPyTVgQCI8MSUp+QaUWMZwBJoGVOsW1t/ENtOBctk+/1FR1Pjb9ya9woMYZvDtVwlusE8lpr1gRbluCg/pYQclm0pa0ovdGvpo56eCQ4Tl+LMrJRuKKBBRH0+YhQ1jEsdjkqEcA4Q66/8GJeRSa/jG7QIJ1LS256luVoUz0lgivgSh1VSHStquW75tawaTY5aYLN2SUMVeyvIp8QeeMa4YyCO7X65oVz00SVR/883vXbZRznbiKyzunLOBv0jqP67SGqOA8+a53UjA/10U986MxSiZdvgz4Rip4fhdUtw4adHDPwSRAYc+A8Q9bXKOWvJ/8X7YdCwmmvxFlNuBA7y/wbbIv1l0CKry2jQJau4rlDFo37K9x0aKXeDEWcW4Rp6YJC4/Iumz4x9nHpFd+RXty26pScNx5nRqVVUIUDmxFjZ8Qpt5WVoehXgBVKMHF4xqcCoU/M4eqa9kCZ4bNCTkAlhn9tKH19ZgGehkLVrvj5rceEwc9F/KdWEOjr6NMLeRo/fQJHlY5soPfLYy3svuFCiQlMoQmj2gdDhxJ2GYinEV6gZ0JTy9rbG+ZZ4/GSOGslSazwddninUWmlZXXqVCKIGZhRMirq6Wsx84M/0BZl/RQE7qDEk5oH++k2/A9fq2MrMDcogESWEvaPVE2QCCHKYc2Z5R8tAcPXZ/C19Mx0gVO2x1MXF8pNnA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
    type: kubernetes.io/basic-auth