apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  destination:
    namespace: sealed-secrets
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    targetRevision: 2.2.0
    chart: sealed-secrets
    directory:
      jsonnet:
        tlas:
          - {}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true