apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: sealed-secrets
    directory:
      jsonnet:
        tlas:
        - name: ""
          value: ""
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.2.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true