apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: awx-admin-password
  namespace: awx
spec:
  encryptedData:
    password: AgA6dSJBKRrpNCtGH566OjFwljCKvYndGEb1i/aOHZZD6Vhf8+oBgyWnpWXGjJTLXEmUKcd7s2HLlGd8CK49YwrJfsZeBdRGTaHMjqT/8gICY4hd7XGCVsxmmaEideZrIb42T5XPAsrK8BHirEvbTs5QY6hyVd6PDscs8pYHD4giDI25Ztt3o+J4OxL7DulllfGAz6zAg/hFD6YJzJIdJqE4jpoHX8OuUdo6rljS7XjSFfMc4jgQi5kqKyQNASdP9DyhgtXHgHONCsnRIF6Yd/LIRXA+pXXVeiX7EcwxjjxUCljOIpws+MI+GBE9z7bbleDwzoquJdjVg8d8ZIwdcF6gUJIFoSs85m8FKFsKePSSn6EL55CgVStnzeKHp2mwqC8b+cOjnX/JnThrXokMzgFe2VvabZ9UOpOzIOft4MWPSbJRT6ERTB9JxyKcTGMXAF1eECa/VeURzEwAQGS5TdPsSweSDU9Ye/udQxeyR71TJuuyNL47kSHmMfg3dmvYrLYZ7ECDMuPOqVLCNYoyvx0cIgae+kmInVq4pt684a4OmTwcja6664M31q9g5AuHBAyvTY9i8Ic4ry6somoCCyYA9GinA3qEPnj6aW7SwtE88Vv9kbsXMJ2WM+lqy7m796asd7OCqSaZZbcDFajE71DTxUlH5vdqdsKpHSN2+vByttMGUk95OU87EPW3auBOl/D1MUS8bxghMeLF80SE
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: awx-admin-password
      namespace: awx