---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: awx-operator
    repoURL: https://ansible.github.io/awx-operator/
    targetRevision: 0.22.0
    helm:
      values: |
        admin_user: admin
        admin_email: tylerklier@gmail.com
        admin_password_secret: awx-admin-password
        ingress_type: route
        route_tls_termination_mechanism: Passthrough
  destination:
    server: "https://kubernetes.default.svc"
    namespace: awx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true   