---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: awx-operator
    repoURL: https://ansible.github.io/awx-operator/
    targetRevision: 0.28.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: awx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true   
