---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: awx
  namespace: awx
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`awx.mushroomkingdom.io`)
      services:
        - name: awx
          port: 7878