---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: pg-test
  namespace: pg-test
spec:
  entryPoints:
    - web
  routes:
    - match: HostSNI(`pg-test.mushroomkingdom.io`)
      services:
        - name: pg-test-primary
          port: 5432