---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: pg-test
  namespace: pg-test
spec:
  entryPoints:
    - postgres
  routes:
    - match: HostSNI(`pg-test.mushroomkingdom.io`)
      services:
        - name: pg-test-primary
          port: 5432
  tls:
    passthrough: true