apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgo
spec:
  destination:
    namespace: pgo
    server: 'https://kubernetes.default.svc'
  source:
    path: installers/kubectl
    repoURL: 'https://github.com/CrunchyData/postgres-operator'
    targetRevision: v4.7.7
    directory:
      include: postgres-operator.yml 
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
