---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 20.8.0
    helm:
      values: |
        additionalArguments:
          - --entryPoints.postgres.address=:5432
          - --serversTransport.insecureSkipVerify=true      
        providers:
          kubernetesIngress:
            enabled: false
        logs:
          general:
            level: ERROR
          access:
            enabled: false        
        service:
          spec:
            loadBalancerIP: 192.168.6.101
        ingressroute:
          dashboard:
            entryPoints:
              - web
            matchRule: Host(`traefik.mushroomkingdom.io`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
            middlewares:
              - name: auth
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true   