apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: traefik
spec:
  encryptedData:
    CLOUDFLARE_DNS_API_TOKEN: AgBTotRf3s6OKeP9q+UgNauGYPgdxDUNlo/9vWT0Mann2GrupNW5HA21Y3LqxgXeMKNWnB034EUUMeq11ZrVPVG7Rn9FrcQUpW7FlnKdoNBtCAFCOpve5PYXmRnxPDRqsPvbsIxtyoSQh8pDTzWtxJv87ryTByJg3yeX90QTVTqBYV1uoOhbmx3UlLgllnd4wy7HtNP47nxnUvDN3A0qEnntPnd1vPm556nhTuLupan9WTU04UMBsmeC2RYRKvyh3vaCLgR2eR2Itput13FSmXYN92Vda5TGHHCPK6xN04LQNvlj1yIXPb6pDiYk6PkoGxQYuODwhm7FkbNEMEQpC6gupWCl9iTbhqDVRGlrm0wRY9PX0voWGWu0ThUCEpWowulVNYaCMom0fvQHN3NpEwmJIk/eW+41JZbTmEn3CR25w9zH5T7lB0Vf15E7H5sygIkbSNOo+qC9pe8ePTc0R9mgQ927cnDuiOoYCX948w/uj5gbprTnmAobAdrLHB/9ZmHUMMa+97JieqjtgEazMbxOQw70pvWeOhsgqaQC6Ry0G3NCseMmh28efUMh7BUx9ft21eywSsPRwhjdooip4faa7jnZiUJAmEQaBKwnzqGspMm5ZnyHtRweTIdppSZJ+DtSiO+DekfN9QaOk1+2UlWfq8UkxBtBxTyfFFJFx7GWyrYRJzWOzVdjfrf/3/LG7fjWWBgeoAdrCHLuWpUzIRSzyLVMCWDQm4bqZPAEY6mFHBCiI5wF
    CLOUDFLARE_EMAIL: AgADa+Cl1dZR9Dv+V/bKDmgCKxpMfNYmCl0GDeiKqohFRjOjX5EBQKy4Y6e1TkCN3BigXbhZye2iONTcnlVofQH39WeqUakAALDdCfjEbp9Hi1XHkSyXTxvH0dk6JhKoCbplr575xCDHI61zVRZUX0o2PmvfclbOCSFVJ1FKmZtUir0B50Z02+eXhJr8xW5xNnhjCw99FuiMrTt1kXEfc5ZJ8lM7ZlWtpKKcjDWberdIdE/8O5xU31bqzP2efwgsIAjqQCffh35HqKdr5DeDjaVSWvInS6WtUxjKWgUpTzD10027q/UB1/j7/MCXGCy233CXtrGrs1jLj3Ka6GQn7xCIsNt9K/HBfLSl+tBvcSS0BouBAbD7kBdNYLcU41MEmcb0erp8RUz3rBRJgqU/vIi99DNxe8HArHZ/pEU97SMrz5ZtAuK6sk4msY3GVXNKEnN4fNOt7WkmviRg25PwrgPCGbIMrSxvVsE4vPSD5ik+ujSVRf3SyBUCUWFz9r1loo9hpQF5nzZ8zAzlLWriWPiPm/rYOgVb7hruckj8Cny/dFD2wa+cZk9vk5/rypdnD0IjuthytwDnnQmnvCZQorgj2LxlY8hPUFEAg0fp0lUv2cyoJIfID7ZtiWs4ALuGV5xoqAjFF0HsfV1LBW4DpngSljpv8j2geERBNgvdW9xTGaZjhBA2B/KM/qFn09D/vfTeLFaIxAZTToR3b3s5HjKN8nFW9g==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: traefik