---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs
  namespace: argocd
spec:
  project: default
  source:
    chart: nfs-subdir-external-provisioner
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    targetRevision: 4.0.16
    helm:
      values: |
        nfs:
          server: 192.168.1.11
          path: /volume1/NFS
        storageClass:
          defaultClass: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true   